version: "2"
services:
    hadoop-master:
        image: hadoop:latest
        container_name: hadoop-master
        hostname: master
        networks:
            hadoop:
                aliases:
                    - master
        ports:
            - "50010:50010"
            - "50020:50020"
            - "50070:50070"
            - "50075:50075"
            - "50090:50090"
            - "8020:8020"
            - "9000:9000"
            - "10020:10020"
            - "8030:8030"
            - "19888:19888"
            - "8031:8031"
            - "8032:8032"
            - "8033:8033"
            - "8040:8040"
            - "8042:8042"
            - "8088:8088"
            - "49707:49707"
            - "2122:2122"
        
    hadoop-slave1: 
        image: hadoop:latest
        container_name: hadoop-slave1
        hostname: slave1
        networks:
            hadoop:
                aliases:
                    - slave1
        expose:
            - "50010"
            - "50020"
            - "50070"
            - "50075"
            - "50090"
            - "8020"
            - "9000"
            - "10020"
            - "8030"
            - "19888"
            - "8031"
            - "8032"
            - "8033"
            - "8040"
            - "8042"
            - "8088"
            - "49707"
            - "2122"
        
    hadoop-slave2: 
        image: hadoop:latest
        container_name: hadoop-slave2
        hostname: slave2
        networks:
            hadoop:
                aliases:
                    - slave2
        expose:
            - "50010"
            - "50020"
            - "50070"
            - "50075"
            - "50090"
            - "8020"
            - "9000"
            - "10020"
            - "8030"
            - "19888"
            - "8031"
            - "8032"
            - "8033"
            - "8040"
            - "8042"
            - "8088"
            - "49707"
            - "2122"
networks: 
    hadoop:
